<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TaxpayerAnalytics.LandingPortal</RootNamespace>
    <AssemblyName>TaxpayerAnalytics.LandingPortal</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharedLibrary\SharedLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="MaxMind.GeoIP2" Version="5.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\db\schema.sql" Link="DbScripts\schema.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
